package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import org.springframework.web.bind.annotation.ModelAttribute;

@Controller // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
            // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping("/demo")
    public String demoForm(Model model)
    {
        model.addAttribute("user", new User());
        return "demo";
    }

    @PostMapping("/demo")
    public Iterable<User> demoPost(@ModelAttribute User user, Model model)
    {
        model.addAttribute("user", user);
        userRepository.save(user);
        return userRepository.findAll();
    }

    @GetMapping("/demo_table")
    public String demoTable(Model model)
    {
        model.addAttribute("user_list", userRepository.findAll());
        return "demo_table";
    }
}